pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - body~=labels:.*semver-patch.*
      - status-success=test
    actions:
      merge:
        method: merge
