addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.4.4")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.10.0")
addSbtPlugin("org.http4s" % "sbt-http4s-org" % "2.0.0")
libraryDependencies ++= Seq("us.oyanglul" %% "dhall-generic" % "0.3.95")
