#!/bin/bash
sbt "++0.26.0;clean;doc"
grep -rl 'html' docs/_site/api | xargs -I {} sed -ie 's/"\/docs/"\/http4s-finagle\/docs/g' {}
grep -rl 'html' docs/_site/api | xargs -I{} sed -ie 's/"\/api/"\/http4s-finagle\/api/g' {}
grep -rl 'html' docs/_site/api | xargs -I{} sed -ie 's/"\/images/"\/http4s-finagle\/images/g' {}
grep -rl 'html' docs/_site/api | xargs -I{} sed -ie 's/"\/js/"\/http4s-finagle\/js/g' {}
grep -rl 'html' docs/_site/api | xargs -I{} sed -ie 's/"\/css/"\/http4s-finagle\/css/g' {}
grep -rl 'html' docs/_site/docs | xargs -I{} sed -ie 's/"\/docs/"\/http4s-finagle\/docs/g' {}
grep -rl 'html' docs/_site/docs | xargs -I{} sed -ie 's/"\/api/"\/http4s-finagle\/api/g' {}
grep -rl 'html' docs/_site/docs | xargs -I{} sed -ie 's/"\/images/"\/http4s-finagle\/images/g' {}
grep -rl 'html' docs/_site/docs | xargs -I{} sed -ie 's/"\/js/"\/http4s-finagle\/js/g' {}
grep -rl 'html' docs/_site/docs | xargs -I{} sed -ie 's/"\/css/"\/http4s-finagle\/css/g' {}
