pages = [{"l":"index.html","n":"Http4s Finagle","t":"Http4s Finagle","d":""},
{"l":"docs/install.html","n":"Installation","t":"Installation","d":""},
{"l":"docs/quick-start.html","n":"Quick Started","t":"Quick Started","d":""},
{"l":"docs/finagle.html","n":"Why Finagle x Http4s?","t":"Why Finagle x Http4s?","d":""},
{"l":"docs/example.html","n":"A Production Ready Example","t":"A Production Ready Example","d":""},
{"l":"api/index.html","n":"API","t":" API","d":"api"},
{"l":"api/org/http4s/finagle.html","n":"org.http4s.finagle","t":"package org.http4s.finagle","d":"org/http4s/finagle"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"Finagle","t":"object Finagle","d":"org/http4s/finagle/Finagle$"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"mkClient","t":"def mkClient[F[_]](dest: String)(F: ConcurrentEffect[F]): Resource[F, Client[F]]","d":"org/http4s/finagle/Finagle$"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"mkClient","t":"def mkClient[F[_]](svc: Service[Request, Response])(F: ConcurrentEffect[F]): Resource[F, Client[F]]","d":"org/http4s/finagle/Finagle$"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"mkService","t":"def mkService[F[_]](route: HttpApp[F])(`evidence$1`: Functor[F], `evidence$2`: ConcurrentEffect[F]): Service[Request, Response]","d":"org/http4s/finagle/Finagle$"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"toHttp4sReq","t":"def toHttp4sReq[F[_]](req: Request): Request[F]","d":"org/http4s/finagle/Finagle$"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"fromHttp4sResponse","t":"def fromHttp4sResponse[F[_]](resp: Response[F])(`evidence$3`: Concurrent[F]): F[Response]","d":"org/http4s/finagle/Finagle$"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"fromHttp4sReq","t":"def fromHttp4sReq[F[_]](req: Request[F])(F: Concurrent[F]): F[Request]","d":"org/http4s/finagle/Finagle$"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"toHttp4sResp","t":"def toHttp4sResp[F[_]](resp: Response): Response[F]","d":"org/http4s/finagle/Finagle$"},
{"l":"docs/index.html","n":"Http4s Finagle","t":"Http4s Finagle","d":""}];