pages = [{"l":"docs/index.html","n":"Http4s Finagle","t":"Http4s Finagle","d":"","k":"static"},
{"l":"docs/install.html","n":"Installation","t":"Installation","d":"","k":"static"},
{"l":"docs/quick-start.html","n":"Quick Started","t":"Quick Started","d":"","k":"static"},
{"l":"docs/finagle.html","n":"Why Finagle x Http4s?","t":"Why Finagle x Http4s?","d":"","k":"static"},
{"l":"docs/example.html","n":"A Production Ready Example","t":"A Production Ready Example","d":"","k":"static"},
{"l":"api/index.html","n":"API","t":"API","d":"","k":"static"},
{"l":"api/org/http4s/finagle.html","n":"org.http4s.finagle","t":"package org.http4s.finagle","d":"org/http4s/finagle","k":"package"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"Finagle","t":"object Finagle","d":"org/http4s/finagle/Finagle$","k":"object"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"fromHttp4sReq","t":"def fromHttp4sReq[F[_]](req: Request[F])(implicit F: Concurrent[F]): F[Request]","d":"org/http4s/finagle/Finagle$","k":"def"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"mkClient","t":"def mkClient[F[_]](dest: String)(implicit F: ConcurrentEffect[F]): Resource[F, Client[F]]","d":"org/http4s/finagle/Finagle$","k":"def"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"mkClient","t":"def mkClient[F[_]](svc: Service[Request, Response])(implicit F: ConcurrentEffect[F]): Resource[F, Client[F]]","d":"org/http4s/finagle/Finagle$","k":"def"},
{"l":"api/org/http4s/finagle/Finagle$.html","n":"mkService","t":"def mkService[F[_]](route: HttpApp[F])(implicit evidence$1: Functor[F], evidence$2: ConcurrentEffect[F]): Service[Request, Response]","d":"org/http4s/finagle/Finagle$","k":"def"},
{"l":"index.html","n":"index","t":"index","d":"","k":"static"}];